# Generated by Django 3.1.7 on 2021-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjrh_bed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedmnagement',
            name='M_A_W_female',
            field=models.CharField(max_length=225, verbose_name='Medical ward A Female'),
        ),
        migrations.AlterField(
            model_name='bedmnagement',
            name='M_A_W_male',
            field=models.CharField(max_length=225, verbose_name='Medical ward A Male'),
        ),
        migrations.AlterField(
            model_name='bedmnagement',
            name='M_B_W_female',
            field=models.CharField(max_length=225, verbose_name='Medical ward B Female'),
        ),
        migrations.AlterField(
            model_name='bedmnagement',
            name='M_B_W_male',
            field=models.CharField(max_length=225, verbose_name='Medical ward B Male'),
        ),
        migrations.AlterField(
            model_name='bedmnagement',
            name='M_C_W_female',
            field=models.CharField(max_length=225, verbose_name='Medical ward C Female'),
        ),
        migrations.AlterField(
            model_name='bedmnagement',
            name='M_C_W_male',
            field=models.CharField(max_length=225, verbose_name='Medical ward C Male'),
        ),
        migrations.AlterField(
            model_name='bedmnagement',
            name='Time',
            field=models.TimeField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='Morning', max_length=24),
        ),
    ]
