# Generated by Django 3.1.7 on 2021-02-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jjrh_bed', '0007_auto_20210220_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='unitname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jjrh_bed.unitname'),
        ),
    ]
